require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '17.0'
use_frameworks! :linkage => :static
use_modular_headers!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAppleSignIn', :path => '../../node_modules/@capacitor-community/apple-sign-in'
  pod 'CapacitorCommunityKeepAwake', :path => '../../node_modules/@capacitor-community/keep-awake'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorScreenOrientation', :path => '../../node_modules/@capacitor/screen-orientation'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'SouthdevsCapacitorGoogleAuth', :path => '../../node_modules/@southdevs/capacitor-google-auth'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'

      # Fix für "Invalid Signature ... not properly signed" beim App-Store-Connect-Upload:
      # Pod-Frameworks (z.B. IONFilesystemLib) bekommen sonst beim Build eine eigene, separate
      # Signatur (oft nur Ad-hoc/"Sign to Run Locally") statt automatisch die Distribution-
      # Signatur der Haupt-App zu übernehmen. Einzelsignierung der Pod-Targets hier deaktivieren -
      # beim Einbetten in die App übernimmt Xcode dann automatisch die korrekte Signatur.
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
